micronaut:
  application:
    name: apiGateway
datasources:
  default:
    driverClassName: org.postgresql.Driver
    db-type: postgresql
    schema-generate: CREATE_DROP
    dialect: POSTGRES
redis.uri: redis://localhost
netty:
  default:
    allocator:
      max-order: 3
elasticsearch.httpHosts: http://localhost:9200,http://127.0.0.2:9200
