micronaut:
  application:
    name: apiGateway
datasources:
  default:
    driverClassName: org.postgresql.Driver
    db-type: postgresql
    schema-generate: NONE
    dialect: POSTGRES
    username: test_user
    password: test_password
    url: 'jdbc:postgresql:postgres'
redis:
  uri: redis://localhost
  password: myredispasswordISn0Ts3Cure

netty:
  default:
    allocator:
      max-order: 3
elasticsearch.httpHosts: http://localhost:9200,http://127.0.0.2:9200
