micronaut:
  application:
    name: helloKotlin
  server:
    port: 9999
#vertx:
#  pg:
#    client:
#      port: 5432
#      host: localhost
#      database: postgres
#      user: test_user
#      password: test_password
#      maxSize: 5
r2dbc:
  datasources:
    default:
      schema-generate: NONE
      dialect: POSTGRES
      url: r2dbc:postgres://localhost:5432/postgres?currentSchema=public
      username: test_user
      password: test_password
netty:
  default:
    allocator:
      max-order: 3

